//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Artikel_Import.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Artikel_Import.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Artikel {
            get {
                object obj = ResourceManager.GetObject("Artikel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Artikel_Allgemein {
            get {
                object obj = ResourceManager.GetObject("Artikel-Allgemein", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Artikel_Einkauf {
            get {
                object obj = ResourceManager.GetObject("Artikel-Einkauf", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Artikel_Verkauf {
            get {
                object obj = ResourceManager.GetObject("Artikel-Verkauf", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This message gets automatically closed in .
        /// </summary>
        internal static string AutoCloseMessagePopUp {
            get {
                return ResourceManager.GetString("AutoCloseMessagePopUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please choose a file first..
        /// </summary>
        internal static string ChooseFileFirst {
            get {
                return ResourceManager.GetString("ChooseFileFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CommandsPerSecond.
        /// </summary>
        internal static string CommandsPerSecond {
            get {
                return ResourceManager.GetString("CommandsPerSecond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure, you want to clear the temp database?.
        /// </summary>
        internal static string ConfirmClearDatabase {
            get {
                return ResourceManager.GetString("ConfirmClearDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure, you want to send the Articles to the Realtime Database? THIS ACTION CAN&apos;T BE REVERSED!.
        /// </summary>
        internal static string ConfirmSendToRuntime {
            get {
                return ResourceManager.GetString("ConfirmSendToRuntime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The CSV is missing rows:.
        /// </summary>
        internal static string CsvIsMissingRows {
            get {
                return ResourceManager.GetString("CsvIsMissingRows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This CSV has too many columns..
        /// </summary>
        internal static string CSVTooManyColumns {
            get {
                return ResourceManager.GetString("CSVTooManyColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a dictionary name..
        /// </summary>
        internal static string EnterDictName {
            get {
                return ResourceManager.GetString("EnterDictName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a name..
        /// </summary>
        internal static string EnterName {
            get {
                return ResourceManager.GetString("EnterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the database password:.
        /// </summary>
        internal static string EnterPassword {
            get {
                return ResourceManager.GetString("EnterPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fatal error .
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errors While Importing .
        /// </summary>
        internal static string ErrorsWhileImporting {
            get {
                return ResourceManager.GetString("ErrorsWhileImporting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ExecutionTook.
        /// </summary>
        internal static string ExecutionTook {
            get {
                return ResourceManager.GetString("ExecutionTook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load Dictionary Keys from CSV. Getting keys from mapping instead..
        /// </summary>
        internal static string FailedToLoadDictionaryKeyFromCSV {
            get {
                return ResourceManager.GetString("FailedToLoadDictionaryKeyFromCSV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong EAN format:.
        /// </summary>
        internal static string FailedToParseEAN {
            get {
                return ResourceManager.GetString("FailedToParseEAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an import error in row .
        /// </summary>
        internal static string ImportErrorRow {
            get {
                return ResourceManager.GetString("ImportErrorRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The mapping is missing pairs:.
        /// </summary>
        internal static string MappingIsMissingEssentialPair {
            get {
                return ResourceManager.GetString("MappingIsMissingEssentialPair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mass Import open CSV....
        /// </summary>
        internal static string MassImportBrowse {
            get {
                return ResourceManager.GetString("MassImportBrowse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mass Import done..
        /// </summary>
        internal static string MassimportDone {
            get {
                return ResourceManager.GetString("MassimportDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to does not match mapping.
        /// </summary>
        internal static string MassImportNotVerified {
            get {
                return ResourceManager.GetString("MassImportNotVerified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting mass import:.
        /// </summary>
        internal static string MassImportStart {
            get {
                return ResourceManager.GetString("MassImportStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to could not find mapping.
        /// </summary>
        internal static string MassImportUnknownMapping {
            get {
                return ResourceManager.GetString("MassImportUnknownMapping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find any values for ArtikelNr..
        /// </summary>
        internal static string MissingArtikelNr {
            get {
                return ResourceManager.GetString("MissingArtikelNr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could nat find any values for BestellNr..
        /// </summary>
        internal static string MissingBestellNr {
            get {
                return ResourceManager.GetString("MissingBestellNr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find any values for Datenlieferant..
        /// </summary>
        internal static string MissingDatenlieferant {
            get {
                return ResourceManager.GetString("MissingDatenlieferant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find any values for EAN..
        /// </summary>
        internal static string MissingEAN {
            get {
                return ResourceManager.GetString("MissingEAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No internet or database connection..
        /// </summary>
        internal static string NoInternetConnection {
            get {
                return ResourceManager.GetString("NoInternetConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Preisgruppen {
            get {
                object obj = ResourceManager.GetObject("Preisgruppen", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RabattEinkauf {
            get {
                object obj = ResourceManager.GetObject("RabattEinkauf", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate.
        /// </summary>
        internal static string Rate {
            get {
                return ResourceManager.GetString("Rate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please import EDE before exporting..
        /// </summary>
        internal static string RememberEDE {
            get {
                return ResourceManager.GetString("RememberEDE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to rename the ArticleNr?.
        /// </summary>
        internal static string RenameArticles {
            get {
                return ResourceManager.GetString("RenameArticles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a mapping..
        /// </summary>
        internal static string SelectMapping {
            get {
                return ResourceManager.GetString("SelectMapping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfull.
        /// </summary>
        internal static string Successfull {
            get {
                return ResourceManager.GetString("Successfull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You entered the wrong password..
        /// </summary>
        internal static string WrongPassword {
            get {
                return ResourceManager.GetString("WrongPassword", resourceCulture);
            }
        }
    }
}
